src/Entity/Serie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SerieRepository")
 */
class Serie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $startedAt;

    /**
     * @ORM\Column(type="date")
     */
    private $EndedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\File(mimeTypes={"image/png", "image/jpeg"})
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_season;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="series")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->startedAt;
    }

    public function setStartedAt(\DateTimeInterface $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->EndedAt;
    }

    public function setEndedAt(\DateTimeInterface $EndedAt): self
    {
        $this->EndedAt = $EndedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getNumberSeason(): ?int
    {
        return $this->number_season;
    }

    public function setNumberSeason(int $number_season): self
    {
        $this->number_season = $number_season;

        return $this;
    }

    public function getCategorieId(): ?Categorie
    {
        return $this->categorie_id;
    }

    public function setCategorieId(?Categorie $categorie_id): self
    {
        $this->categorie_id = $categorie_id;

        return $this;
    }
}

src/Form/SerieType.php
<?php

namespace App\Form;

use App\Entity\Serie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SerieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => ['placeholder' => 'Nom de la série'],
                'label' => false
            ])
            ->add('startedAt')
            ->add('EndedAt')
            ->add('image', FileType::class)
            ->add('number_season')
            // ->add('categorie_id')
            ->add('submit', SubmitType::class, [
                'label' => 'Ajouter une nouvelle série',
                'attr'=> ["class" => 'btn btn-primary']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Serie::class,
        ]);
    }
}

src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Serie;
use App\Form\SerieType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;

class SerieController extends AbstractController
{
    /**
     * @Route("/serie", name="serie")
     */
    public function index(Request $request, EntityManagerInterface $entityManager)  
    {

        $serie = new Serie();

        $serieRepository = $this->getDoctrine()->getRepository(Serie::class);
        $series = $serieRepository->findAll();


        $categorieRepository = $this->getDoctrine()->getRepository(Categorie::class);
        $allCategories = $categorieRepository->findAll();
        


        $serieForm = $this->createForm(SerieType::class, $serie);
        $serieForm->handleRequest($request);


        if($serieForm->isSubmitted() && $serieForm->isValid()){

            $serie = $serieForm->getData();
            $categorieId = $categorieRepository->find($request->request->get('categories'));
            $serie->setCategorieId($categorieId);
            
            // $image = $serie->getImage();
            $image = $serieForm->get('image')->getData();
            $imageName = md5(uniqid()).'.'.$image->guessExtension();
            $image->move($this->getParameter('upload_files'), 
            $imageName);
            $serie->setImage($imageName);

            
            $entityManager->persist($serie);
            $entityManager->flush();

            return $this->redirectToRoute('serie');

        }

        dump($series);

        return $this->render('serie/index.html.twig', [
            'serieForm' => $serieForm->createView(),
            'categories' => $allCategories,
            'series' => $series
        ]);
    }

    /**
     * @Route("/serie/{id}", name="fiche")
     */
    public function selectedSerie($id, Request $request, EntityManagerInterface $entityManager) {


        $serie = $this->getDoctrine()->getRepository(Serie::class)->find($id);

        $categorieRepository = $this->getDoctrine()->getRepository(Categorie::class);
        $categories = $categorieRepository->findAll();

        $updateSerieForm = $this->createForm(SerieType::class, $serie);
        $updateSerieForm->handleRequest($request);

        // $serie->setImage(new File($this->getParameter('upload_files').'/'.$serie->getImage()));

        return $this->render('serie/fiche.html.twig', [
            'serie' => $serie,
            'serieForm' => $updateSerieForm->createView(),
            'categories' => $categories
        ]);
    }

    /**
     * @Route("/removeserie/{id}", name="removeserie")
     */
    public function remove($id, Request $request, EntityManagerInterface $entityManager){
        $serie = $this->getDoctrine()->getRepository(Serie::class)->find($id);

        $entityManager->remove($serie);
        $entityManager->flush();

        return $this->redirectToRoute('home');

    }
}

templates/serie/fiche.html.twig
{% extends 'base.html.twig' %}

{% block title %}Series{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card" style="width: 50%;">
                <div class="card-header">
                    <h3> {{serie.name}} </h3>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Date de début : {{serie.startedAt | date('d/m/Y')}} <br>
                        Date de fin : {{serie.endedAt | date('d/m/Y')}} <br>
                        Nombre de saison : {{serie.numberSeason}} <br>
                        Categorie : {{serie.categorieId.name}}
                    </p>
                </div>
                <div class="card-footer">
                    <button class="btn btn-danger"> <a href="{{path('removeserie', {id: serie.id})}}" style="color: white;">Supprimer la série</a></button>
                </div>
            </div>
        </div>
        <div class="col-6">
            {# <h3>Modifier la série</h3><br> #}
            {{form_start(serieForm)}}
            {{form_row(serieForm.name)}}
            <label for="categories">Categorie :</label>
            <select name="categories" id="categories">
                {% for categorie in categories %}
                <option value="{{categorie.id}}">{{categorie.name}}</option>
                {% endfor %}
            </select>
            {{form_end(serieForm)}}
        </div>
    </div>
    
</div>

{% endblock %}

templates/serie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Series{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-6">
                {% for serie in series %}
                    <div class="card">
                        <div class="card-header">
                            <h3> {{serie.name}} </h3>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                Date de début : {{serie.startedAt | date('d/m/Y')}} <br>
                                Date de fin : {{serie.endedAt | date('d/m/Y')}} <br>
                                Nombre de saison : {{serie.numberSeason}} <br>
                                Categorie : {{serie.categorieId.name}}
                            </p>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-warning"> <a href="{{path('fiche', {id: serie.id})}}" style="color: white;">Voir sa fiche</a></button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-6">
                <h3>Ajouter une série</h3>
                {{form_start(serieForm)}}
                {{form_row(serieForm.name)}}
                <label for="categories">Categorie :</label>
                <select name="categories" id="categories">
                    {% for categorie in categories %}
                        <option value="{{categorie.id}}">{{categorie.name}}</option>
                    {% endfor %}
                </select>
                {{form_end(serieForm)}}
            </div>
        </div>
    </div>


{% endblock %}